Add zh-TW locale
thingsboard/flutter_thingsboard_app pull request #68
Opened 2024-03-24 13:14 UTC by maksonlee

2024-07-09 08:51 UTC, ybeshkarov requested changes
Hi @maksonlee,

Thanks for your PR!

Could you please fix the comments and put the dev branch as a target? 
Thanks!

2024-07-09 08:51 UTC, ybeshkarov commented on l10n.yaml
> +nullable-getter: false
Please add new line

2024-07-09 08:51 UTC, ybeshkarov commented on lib/l10n/intl_zh_CN.arb
> +}
Here as well

2024-07-09 08:51 UTC, ybeshkarov commented on lib/l10n/intl_zh_TW.arb
> +}
And here

2024-07-11 15:32 UTC, maksonlee commented on l10n.yaml
> +nullable-getter: false
Done

2024-07-11 15:32 UTC, maksonlee commented on lib/l10n/intl_zh_CN.arb
> +}
Done

2024-07-11 15:32 UTC, maksonlee commented on lib/l10n/intl_zh_TW.arb
> +}
Done

2024-07-11 18:29 UTC, merged