Add Arabic locale
thingsboard/flutter_thingsboard_app pull request #96
Opened 2024-06-17 16:13 UTC by salemaljebaly

2024-06-17 16:20 UTC, salemaljebaly commented
I add ar support to app, check it when you have time.
@ybeshkarov

2024-07-09 08:41 UTC, ybeshkarov requested changes

2024-07-09 08:41 UTC, ybeshkarov commented on lib/l10n/intl_ar.arb
> +}
Add a new line please

2024-07-09 08:42 UTC, ybeshkarov commented
Looks good!

Could you please point the dev branch as a target? 

Thanks.

2024-07-09 09:08 UTC, ybeshkarov commented on lib/l10n/intl_ar.arb
> +}
Nope, just add a 113 empty line

2024-07-09 09:31 UTC, ybeshkarov approved these changes

2024-07-09 09:32 UTC, merged